### ISSUE TITLE
add support for esp32 wifi bluetooth

### ISSUE THREAD

**Issue by yangminglong** [tinygo-org/tinygo#3216] opened 2022-10-04 13:45 UTC
add support for esp32 wifi bluetooth

**Comment by aykevl** [comment] 2023-05-01 15:15
Duplicate of https://github.com/tinygo-org/tinygo/issues/2024.

**Closed as completed by aykevl** 2023-05-01 15:15 UTC

**Comment by huanglishi** [comment] 2025-02-21 04:06
Hope it can support wifi, otherwise tinygo is useless on the esp32 series
