### ISSUE TITLE
Possibly spurious error: LLVM ERROR: Coroutines cannot handle non static allocas yet

### ISSUE THREAD

**Issue by justinclift** [tinygo-org/tinygo#421] opened 2019-06-23 06:24 UTC
Came across an interesting LLVM ERROR while adjusting the repulsion demo to use JS timers instead of Go created callbacks.

```
$ tinygo build -target wasm -gc conservative -no-debug -o html/test.wasm canvas/main.go
LLVM ERROR: Coroutines cannot handle non static allocas yet
```

Instead of this being a cut-n-dried case of something being wrong with the code, this is turning up after **working** code (that compiles fine) has a non-useful part commented out.  eg there's no functional change to the code.  No change in what touches globals, etc.

Seems like something isn't quite right yet. :wink:

The full code (compiles ok): https://github.com/justinclift/wasm-experiments/blob/88ef10af6523556786f8bc44b1aea86ce2c198be/canvas/main.go

The code section to comment out, to trigger this problem: https://github.com/justinclift/wasm-experiments/blob/88ef10af6523556786f8bc44b1aea86ce2c198be/canvas/main.go#L46-L56

**Comment by justinclift** [comment] 2019-06-23 06:31
Note - the easiest way to workaround the problem is to remove the `chan` completely.  Doesn't seem to be needed these days anyway. :wink:

**Comment by aykevl** [comment] 2019-06-24 12:27
That's interesting. It is probably still caused by the `defer` somehow (the second?) because defer does a stack allocation. The easy way to fix this is to use heap allocation, but most defer statements can easily be stack allocated.

A similar problem existed in the gc toolchain but seems to be fixed now: https://github.com/golang/go/issues/14939

**Comment by justinclift** [comment] 2019-06-24 14:19
> The easy way to fix this is to use heap allocation ...

Are you meaning create `mouseMoveEvt` using `new()`?

**Comment by deadprogram** [comment] 2019-09-17 10:51
Is this issue and #234 the same issue? Also, is this still an issue with the latest `dev` branch?

**Comment by justinclift** [comment] 2019-09-17 13:45
Not sure atm.  I'll have time to get back into TinyGo at the start of next month, so hopefully it can wait until then? :smile:

**Comment by jadr2ddude** [comment] 2019-09-27 14:46
This remains a major limitation. For those who do not know what a static alloca is, a static alloca is a stack allocation that occurs in the entry basic block. Therefore, if the alloca is outside the entry block then we cannot do coroutine lowering at the moment. While implementing blocking select, I ran into this. This definitely is present right now.

**Comment by aykevl** [comment] 2019-09-30 17:26
Allocas should really be moved into the entry block if possible (which is almost always the case). Take a look here for how it can be done: https://github.com/tinygo-org/tinygo/pull/359

**Comment by jaddr2line** [comment] 2020-03-01 18:15
After #828, there should not be any generated non-static allocas left.

**Comment by aykevl** [comment] 2020-03-01 19:40
Closing this issue too, see https://github.com/tinygo-org/tinygo/issues/234#issuecomment-593136349.

**Closed by aykevl** 2020-03-01 19:40 UTC
Labels: bug
