### ISSUE TITLE
error: could not read version from GOROOT (/usr/local/go): Invalid go version output

### ISSUE THREAD

**Issue by Techno-Fox** [tinygo-org/tinygo#2116] opened 2021-09-15 18:23 UTC
This error appears when trying to use tinygo

go version: go1.17.1

```
error: could not read version from GOROOT (/usr/local/go): Invalid go version output:
// Code generated by go tool dist; DO NOT EDIT.

package sys

const StackGuardMultiplierDefault = 1

```

**Comment by aykevl** [comment] 2021-09-15 18:58
Duplicate of https://github.com/tinygo-org/tinygo/issues/2059. This has been fixed in the dev branch so will be fixed in the next release. For now, please use Go 1.16 until the next release.

**Closed as completed by aykevl** 2021-09-15 18:58 UTC
