### ISSUE TITLE
Will there be PWM support for ESP32 Core Board?

### ISSUE THREAD

**Issue by eleimt** [tinygo-org/tinygo#4653] opened 2024-12-11 11:03 UTC
Hello.
Thanks for the project, it's very cool, I also follow the news in Mastodon. Tell me, should we expect PWM support for the ESP32 Core board?

**Comment by deadprogram** [comment] 2024-12-11 11:30
Duplicate of #4124

**Closed as completed by deadprogram** 2024-12-11 11:30 UTC
Labels: duplicate, esp32
