### ISSUE TITLE
LLVM ERROR: Coroutines cannot handle non static allocas yet

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [tinygo-org/tinygo#234] opened 2019-03-12 15:44 UTC
**First of all, because normal Go generates super big size wasm bundle, I wanted to use tinygo .**

I tried to run and test wasm bundling using the following example(in [https://github.com/golang/go/wiki/WebAssembly](https://github.com/golang/go/wiki/WebAssembly)) of 

**[https://github.com/bobcob7/wasm-rotating-cube](https://github.com/bobcob7/wasm-rotating-cube)**

Because I am using MacOS and cannot install llvm and tinygo(I couldn't install),
I ran tinygo inside docker container. However, although This is pretty very basic example, I got this error!? Did I something wrong?  or tinygo hasn't support it yet?

**"LLVM ERROR: Coroutines cannot handle non static allocas yet"**

**Comment by deadprogram** [comment] 2019-03-19 06:03
Looks like this feature is not yet fully implemented. Tagging as such.

**Comment by aykevl** [comment] 2019-03-19 11:33
This error is caused by a limitation in the coroutine support of LLVM, not in TinyGo (although TinyGo might be able to fix some of it). I'm surprised to see it, because I thought most of those issues were gone now.
Looking at the code, it also relies on `js.NewCallback` which is not yet supported.

**Comment by jaddr2line** [comment] 2020-03-01 18:15
After #828, there should not be any generated non-static allocas left.

**Comment by aykevl** [comment] 2020-03-01 19:38
That's right. I believe this bug has been fixed now and there is testing in place to avoid future recurrences (see #774). Please comment if there are still instances of it left.

**Closed by aykevl** 2020-03-01 19:38 UTC
Labels: enhancement

**Comment by jaddr2line** [comment] 2020-03-01 20:25
The old `coroutines` implementation does still split allocas sometimes I think, so yes there may still be some issues. The new implementation does not.
