### ISSUE TITLE
Pin Interrupts with Arduino Uno

### ISSUE THREAD

**Issue by boisgera** [tinygo-org/tinygo#3279] opened 2022-11-08 16:27 UTC
Hi everyone! 

I am using TinyGo for Arduino Uno and I am having a great time! Thanks to everyone involved in this project 👍

The only hurdle I have so far is the management of GPIO interrupts. I am following the doc [here](https://tinygo.org/docs/concepts/peripherals/gpio/#interrupts-on-pin-changes) ; but Pin seems to have no `SetInterrupt` method if I am to believe the compiler (tinygo v0.26) or VS Code ([properly configured](https://tinygo.org/docs/guides/ide-integration/vscode/) AFAICT). Am I missing something obvious? 🤔

Regards,

Sébastien

**Comment by aykevl** [comment] 2022-11-17 13:31
Unfortunately, `SetInterrupt` has not yet been implemented on AVR chips. The hardware supports it so it's just a matter of implementing it.

**Comment by boisgera** [comment] 2022-11-17 15:34
> Unfortunately, `SetInterrupt` has not yet been implemented on AVR chips. The hardware supports it so it's just a matter of implementing it.

Ah, OK, good to know! I am afraid that I am not familiar enough with TinyGo internals to be of any help here.
Thank you for the reply!

**Comment by BerndCzech** [comment] 2022-12-26 23:26
I would be willing to have a look as I have an Uno here.

**Comment by deadprogram** [comment] 2023-05-18 18:12
Duplicate of #3145 so now closing.

**Closed as completed by deadprogram** 2023-05-18 18:12 UTC
Labels: duplicate, enhancement, avr
