### ISSUE TITLE
PANIC using mcp2515 CAN SPI config on atmega328p 

### ISSUE THREAD

**Issue by jadefox10200** [tinygo-org/tinygo#2414] opened 2021-12-20 18:24 UTC
I am getting the following panic: 
```
panic: compiler: could not store type code number inside interface type code

goroutine 12 [running]:
github.com/tinygo-org/tinygo/transform.LowerReflect({0x9b95f70})
	/Users/distiller/project/transform/reflect.go:185 +0x905
github.com/tinygo-org/tinygo/transform.Optimize({0xc001b2fdc8}, 0xc0002dc090, 0x2, 0x0, 0x5)
	/Users/distiller/project/transform/optimizer.go:91 +0x4a5
github.com/tinygo-org/tinygo/builder.optimizeProgram({0x796f980}, 0xc0002dc090)
	/Users/distiller/project/builder/build.go:740 +0x1ed
github.com/tinygo-org/tinygo/builder.Build.func2(0x0)
	/Users/distiller/project/builder/build.go:386 +0x657
github.com/tinygo-org/tinygo/builder.jobWorker(0x0, 0x0)
	/Users/distiller/project/builder/jobs.go:182 +0xad
created by github.com/tinygo-org/tinygo/builder.runJobs
	/Users/distiller/project/builder/jobs.go:101 +0x1a5
```

I am using the following code: 
```
package main

import (
	"machine"
	"time"

	mcp "tinygo.org/x/drivers/mcp2515"
)

func main() {

	cs10 := machine.PB2

	err := machine.SPI0.Configure(machine.SPIConfig{
		Frequency: 115200,
	})

	if err != nil {
		println(err)
		return
	}

	//pointer to a Device is returned. Must pass chip select pin and the SPI0
	can := mcp.New(machine.SPI0, cs10)

	//configure the mcp2515 device
	can.Configure()

	//start it:
	err = can.Begin(mcp.CAN500kBps, mcp.Clock8MHz)
	if err != nil {
		println("Error on begin")
		println(err)
	}

	//loop through and check for messages: 
	for {
		if can.Received() {
			msg, err := can.Rx()
			if err != nil {
				println("ERROR ON RCV:")
				println(err)
				continue
			}
			println("GOT DATA:")
			println(string(msg.Data))
			time.Sleep(500 * time.Millisecond)
		}
	}

}
```
It appears this panic is happening on the Begin() function. It is happening during the flash. I tested this code on a PICO board and it loads fine (I can't use the PICO though because I do not have the CAN hardware). The biggest difference I can see is how the SPI config is done between the two boards. I honestly don't understand exactly what is happening with the compiler though to know where the issue is.

**Comment by aykevl** [comment] 2021-12-28 22:22
Please see https://github.com/tinygo-org/tinygo/issues/2169, this is a duplicate of that bug.

**Closed as completed by aykevl** 2021-12-28 22:22 UTC
