### ISSUE TITLE
ESP32 WiFi support

### ISSUE THREAD

**Issue by andoks** [tinygo-org/tinygo#1683] opened 2021-03-04 23:53 UTC
Same request as #1427 but for ESP32 :smiley: 

Personally I would like to use tinygo with my Wemos Lolin 32 board; I am holding back on making a board support wish issue for that board for now, since I primarily want to use it for projects with WiFi connectivity.

**Comment by aykevl** [comment] 2023-05-01 15:14
Duplicate of https://github.com/tinygo-org/tinygo/issues/2024.

**Closed as completed** 2023-05-01 15:14 UTC
Labels: enhancement, esp32
