### ISSUE TITLE
[runtime error: out of memory] due to repeated call to demo splitter method

### ISSUE THREAD

**Issue by Kusers** [tinygo-org/tinygo#1327] opened 2020-08-29 08:03 UTC
Error screenshot
https://github.com/Kusers/tinygoDemo/blob/master/runerr.png
javascript code
https://github.com/Kusers/tinygoDemo/blob/master/run_err_js.txt
How can we solve this problem? I look forward to your reply. Thank you very much

**Comment by aykevl** [comment] 2020-08-29 11:38
Passing data between JavaScript and WebAssembly (Go) currently leaks memory. You can slow it down a bit with the `-heap-size` parameter.

**Comment by Kusers** [comment] 2020-08-31 01:12
If I use C language, will it still happen?

**Comment by deadprogram** [comment] 2020-09-12 09:42
@Kusers this is a really a general problem with memory management and any WASM code that wants to pass data to/from JavaScript, regardless of what was used to compile it.

**Comment by FrankReh** [comment] 2020-10-14 22:59
The memory leak caused by having no finalizers called? I've run into that today.

Does getting a gc for wasm to understand objects that are being freed, and keeping track of their finalizers, require knowledge of the LLVM side of things or should it be enough to know the Go and JavaScript side of things?

I'm not even sure the conservative gc is being used for the wasm target. I saw a question about it early last year but the answer was that channels and reflection were first on the TODO list.

I don't know what the setup time is for a wasm instantiation but is a viable alternative to let the entire instance be collected by the JavaScript VM and start a new wasm instance when memory gets low?

**Comment by deadprogram** [comment] 2021-03-08 12:49
This has been released with v0.17.0 so now closing. Thanks!

**Closed as completed by deadprogram** 2021-03-08 12:49 UTC
Labels: wasm
