### ISSUE TITLE
package runtime/volatile: missing function body

### ISSUE THREAD

**Issue by goelvatsal** [tinygo-org/tinygo#3077] opened 2022-08-16 02:27 UTC
Plugin version: TinyGo 0.25.0
IDE name and version: IntelliJ GoLand 2022.2.1
OS name: MacOS Monterey

GOPATH: /Users/goel01/go/
GOROOT (if needed): /usr/local/Cellar/go/1.18.5/libexec/
Project location: /Users/goel01/go/src/github.com/PacktPublishing/Creative-DIY-Microcontroller-Projects-with-TinyGo-and-WebAssembly

I'm trying to run a program called [water-level-sensor-example](https://github.com/PacktPublishing/Creative-DIY-Microcontroller-Projects-with-TinyGo-and-WebAssembly/tree/master/Chapter04/water-level-sensor-example), with [water-level-sensor](https://github.com/PacktPublishing/Creative-DIY-Microcontroller-Projects-with-TinyGo-and-WebAssembly/tree/master/Chapter04/water-level-sensor) being a library for the former. My IDE (GoLand) asks me to download a package called runtime/volatile. After downloading it, I go to run the program again, and it outputs 8 errors stating that there is a "missing function body". Thanks in advance. I can provide more information in case you need it.

<img width="1060" alt="Screen Shot 2022-08-15 at 10 21 03 PM" src="https://user-images.githubusercontent.com/31752052/184785185-54a819c6-6a92-49e9-a992-33434e2ecb65.png">

**Comment by deadprogram** [comment] 2022-08-16 18:02
This looks like an issue with the GoLand plugin, which I am not really very familiar with. Perhaps it is not configured properly? I'd suggest you use the resources listed here https://plugins.jetbrains.com/plugin/16915-tinygo to contact the maintainers of the plugin.

**Comment by aykevl** [comment] 2022-08-31 20:51
> My IDE (GoLand) asks me to download a package called runtime/volatile.

That looks like a bug in the TinyGo extension for GoLand. It shouldn't try to download a standard library module. (EDIT: but I might be wrong, maybe that's when it downloads TinyGo itself?)

@nickfromXXII I think you work on this plugin? Can you take a look?

**Comment by goelvatsal** [comment] 2022-09-04 22:11
> This looks like an issue with the GoLand plugin, which I am not really very familiar with. Perhaps it is not configured properly? I'd suggest you use the resources listed here https://plugins.jetbrains.com/plugin/16915-tinygo to contact the maintainers of the plugin.

Sorry for the very late response, I can't seem to find the managers of the TinyGo plugin on the website, it just says that the vendor is JetBrains.

**Comment by nickfromXXII** [comment] 2022-09-05 07:38
@goelvatsal Yes, it seems to be a plugin issue. It would be nice if you could provide more information about your problem by submitting a ticket on the JetBrains tracker at https://youtrack.jetbrains.com/issues/GO. Thanks!

**Comment by nickfromXXII** [comment] 2022-09-05 08:06
@goelvatsal Sorry for inconvenience, it seems to be a plugin issue. It would be nice if you could provide concrete steps for reproducing the problem by submitting a ticket on the JetBrains tracker at https://youtrack.jetbrains.com/issues/GO. Thank you!

**Comment by deadprogram** [comment] 2022-09-10 10:28
Closing as specific to JetBrains plugin. Please open a ticket there as requested. Thank you!

**Closed as completed by deadprogram** 2022-09-10 10:28 UTC
