### ISSUE TITLE
esp8266 wifi support

### ISSUE THREAD

**Issue by mengyan258** [tinygo-org/tinygo#4199] opened 2024-03-19 02:04 UTC
I have searched for many similar articles before, but I cannot find the wifi support for ESP8266 from Tinygo. This has forced me to give up the choice of Tinygo. In the latest progress of Tinygo, will there still be support for ESP8266's wifi? I am looking forward to it, after all, golang is currently my first development language.

**Comment by aykevl** [comment] 2024-03-19 10:35
This is a duplicate of #1427. Please see that issue for more discussion around this.

**Closed as not planned by aykevl** 2024-03-19 10:35 UTC
