### ISSUE TITLE
On the ESP32 requires the use of bluetooth and WIFI,What's the solution

### ISSUE THREAD

**Issue by onism-up** [tinygo-org/tinygo#3396] opened 2023-01-18 02:50 UTC

**Comment by alvonwong** [comment] 2023-01-18 13:34
i think that's a great but hard job for developers . i expect it  on raspberry pi pico .

**Comment by onism-up** [comment] 2023-01-19 02:55
> i think that's a great but hard job for developers . i expect it on raspberry pi pico .

Yes, TinyGo still needs a period of growth

**Comment by aykevl** [comment] 2023-05-01 15:15
Duplicate of https://github.com/tinygo-org/tinygo/issues/2024.

**Closed as completed by aykevl** 2023-05-01 15:15 UTC
Labels: duplicate, enhancement, esp32
