### ISSUE TITLE
"make test-corpus" fails on linux in google/go-patchutils?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2842] opened 2022-05-09 14:47 UTC
On my fresh ubuntu 22.04 VM, with a freshly built dev, "make test-corpus" crashes if
google/go-patchutils is in corpus.yaml.
(Evidently that is a recent addition, but not that recent, https://github.com/tinygo-org/tinygo/commit/cbfa85be6ad018b447f2c47401f4ebf8193b0887 )

Here's a log.
[bad.txt](https://github.com/tinygo-org/tinygo/files/8652720/bad.txt)

**Comment by dkegel-fastly** [comment] 2022-05-09 14:50
A corpus.yaml containing just google/go-patchutils fails in the linux vm but doesn't fail on my mac (outside the vm, I mean).

**Comment by dankegel** [comment] 2022-05-09 17:08
Confirming it fails on a plain old linux box, no VM involved.

**Comment by dgryski** [comment] 2022-05-09 17:40
I'll take a look at this.

**Comment by dgryski** [comment] 2022-05-10 14:43
Passes on mac. Will need to test this in a VirtualBox Ubuntu.

**Comment by dgryski** [comment] 2022-05-10 21:14
Got this failing on my ubuntu vm.  It's an error in *building* the code, not in *running* the code.  Interesting.

**Comment by dgryski** [comment] 2022-05-10 21:53
```
2022/05/10 21:49:52 compiling: github.com/google/go-patchutils$string.219
```
Possibly the function that's failing to compile.

**Comment by dgryski** [comment] 2022-05-11 04:22
With llvm-13 on Linux:
```
2022/05/11 04:19:26 compiling: github.com/google/go-patchutils$string.219
panic: runtime error: index out of range [-1]

goroutine 86 [running]:
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc00460e000, 0xc002f9bc20, {0xc004ea3e90, 0x4, 0x0?}, 0xc004245b30, {0xc004d054a0, 0x14})
	/home/dgryski/go/src/github.com/tinygo-org/tinygo/interp/interpreter.go:902 +0x61f9
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc00460e000, 0xc002f9ba40, {0xc00414d8d0, 0x3, 0x0?}, 0xc004245680, {0xc004ef7ff0, 0x10})
	/home/dgryski/go/src/github.com/tinygo-org/tinygo/interp/interpreter.go:501 +0x80b4
```

where line 902 is:
```
        return nil, mem, r.errorAt(bb.instructions[len(bb.instructions)-1], errors.New("interp: reached end of basic block without terminator"))
```

So, `len(bb.instructions) == 0`.

**Comment by dgryski** [comment] 2022-05-11 04:38
Hmm... couldn't get that to fail again with llvm, but decided to look at the llvm ir

```
@"github.com/google/go-patchutils$string.219" = internal unnamed_addr constant [13 x i8] c"test_examples", align 1
```

Can't say that's particularly useful...

**Comment by dgryski** [comment] 2022-05-11 20:36
Huh, so this segfault still happens using llvm11 at `e668c8c1a7eebfa9f396ca79e8023e11f9e51532`, the first commit where `os.Chdir` was added (which is needed for `go-patchutils` to build/run).

**Comment by dgryski** [comment] 2022-05-11 20:50
And go-patchutils was added in Feburary.  Seems like this particular repo *never* worked on Linux :/

**Comment by dgryski** [comment] 2022-05-16 19:02
Smaller reproducer:
```
package main

import (
	"os"
)


func init() {
        testFilesDir := "test_examples"
	os.Chdir(testFilesDir)
}


func main() {
	println("hello, world")
}
```

**Comment by aykevl** [comment] 2022-05-19 12:16
I can reproduce this using `tinygo build -o test.ll ./tmp/issue2842.go` on Linux, it crashes with a segmentation fault or an OOM. So it's pretty bad.

I'm now rebuilding LLVM with assertions enabled (because my previous LLVM build got accidentally trashed, fixed in #2838). After that, I can hopefully more easily see what's going on.

(Assertions can be enabled by passing `ASSERT=1` while building LLVM and are very helpful to catch many common mistakes).

**Comment by aykevl** [comment] 2022-05-21 01:38
Well of course it triggered an assert:

```
tinygo: /home/ayke/src/github.com/tinygo-org/tinygo/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
SIGABRT: abort
PC=0x7f4a15e3ace1 m=7 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 25 [syscall]:
runtime.cgocall(0xd94e90, 0xc0018a90c8)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0018a90a0 sp=0xc0018a9068 pc=0xa3385c
tinygo.org/x/go-llvm._Cfunc_LLVMCountParams(0x7f49cd8817c0)
        _cgo_gotypes.go:4103 +0x4c fp=0xc0018a90c8 sp=0xc0018a90a0 pc=0xc4462c
tinygo.org/x/go-llvm.Value.ParamsCount.func1({0xd?})
        /home/ayke/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20220420140351-512c94c1e71f/ir.go:1203 +0x3f fp=0xc0018a9100 sp=0xc0018a90c8 pc=0xc5ecdf
tinygo.org/x/go-llvm.Value.ParamsCount({0xd?})
        /home/ayke/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20220420140351-512c94c1e71f/ir.go:1203 +0x19 fp=0xc0018a9118 sp=0xc0018a9100 pc=0xc5ec79
tinygo.org/x/go-llvm.Value.Params({0x5b023c0?})
        /home/ayke/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20220420140351-512c94c1e71f/ir.go:1205 +0x1e fp=0xc0018a9160 sp=0xc0018a9118 pc=0xc5ed3e
github.com/tinygo-org/tinygo/interp.(*runner).compileFunction(0xc00156a000, {0xc001c1e000?})
        /home/ayke/src/github.com/tinygo-org/tinygo/interp/compiler.go:66 +0x65 fp=0xc0018a9498 sp=0xc0018a9160 pc=0xd10dc5
github.com/tinygo-org/tinygo/interp.(*runner).getFunction(0xc00156a000, {0x0?})
        /home/ayke/src/github.com/tinygo-org/tinygo/interp/interp.go:280 +0x4e fp=0xc0018a94d0 sp=0xc0018a9498 pc=0xd1608e
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc00156a000, 0xc000676aa0, {0xc00297d050, 0x3, 0x0?}, 0xc002b8e120, {0xc001a684d0, 0xc})
        /home/ayke/src/github.com/tinygo-org/tinygo/interp/interpreter.go:195 +0x34f9 fp=0xc0018aa0f8 sp=0xc0018a94d0 pc=0xd19779
[...etc...]
```

**Comment by aykevl** [comment] 2022-05-21 01:44
To debug without assertions enabled, add this small patch:

```diff
diff --git a/interp/compiler.go b/interp/compiler.go
index 20723c64..e9008c89 100644
--- a/interp/compiler.go
+++ b/interp/compiler.go
@@ -60,6 +60,11 @@ func (inst *instruction) String() string {
 // version of the function. As far as possible, all operands are preprocessed so
 // that the interpreter doesn't have to call into LLVM.
 func (r *runner) compileFunction(llvmFn llvm.Value) *function {
+       if llvmFn.IsAFunction().IsNil() {
+               llvmFn.Dump()
+               println()
+               panic("not a function")
+       }
        fn := &function{
                llvmFn: llvmFn,
                name:   llvmFn.Name(),
```

This shows it's trying to compile the following as a function:

```llvm
@"main$string.2" = internal unnamed_addr constant [13 x i8] c"test_examples", align 1
```

Therefore, this must be a bug in interp.

**Comment by dgryski** [comment] 2022-05-21 05:15
I had gotten this far in my investigation: I had already figured out interp was trying to call a string constant as a function, but got totally lost trying to figure out where or how that happened :(

**Comment by aykevl** [comment] 2022-05-21 12:49
Ah, okay, I missed that.
In any case, I can recommend building LLVM with `ASSERT=1` to more easily debug these kinds of issues :) (you'll get an early panic whenever something bad happens).

**Comment by aykevl** [comment] 2022-05-21 13:04
Some more debugging sheds some light on the underlying problem:

```
# main
/usr/local/go1.18/src/syscall/zsyscall_linux_amd64.go:270:21: expected a function
  %9 = call i64 asm sideeffect inteldialect "syscall", "={rax},0,{rdi},{rsi},{rdx},~{rcx},~{r11}"(i64 80, i64 %8, i64 0, i64 0), !dbg !1794

traceback:
/usr/local/go1.18/src/syscall/zsyscall_linux_amd64.go:270:21:
  %9 = call i64 asm sideeffect inteldialect "syscall", "={rax},0,{rdi},{rsi},{rdx},~{rcx},~{r11}"(i64 80, i64 %8, i64 0, i64 0), !dbg !1794
/home/ayke/src/github.com/tinygo-org/tinygo/src/os/file_anyos.go:36:23:
  %2 = call %runtime._interface @syscall.Chdir(i8* %dir.data, i64 %dir.len, i8* undef), !dbg !1781
/home/ayke/src/github.com/tinygo-org/tinygo/tmp:
  %1 = call %runtime._interface @os.Chdir(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @"main$string.2", i32 0, i32 0), i64 13, i8* undef), !dbg !1776
```

**Comment by aykevl** [comment] 2022-05-21 13:58
https://github.com/tinygo-org/tinygo/pull/2863 should fix this bug.

**Closed as completed** 2022-06-29 13:50 UTC
Labels: bug
