### ISSUE TITLE
Is there any useable serialize/unserialize tools in tinygo?

### ISSUE THREAD

**Issue by fractus-chain** [tinygo-org/tinygo#418] opened 2019-06-21 03:58 UTC
msgpack can not compile in tinygo and there is no builtin tools like encoding/json encoding/gob.

**Comment by aykevl** [comment] 2019-06-21 14:25
Not that I'm aware of, but you can take a look at serialization tools that do not use reflection. Reflection still has poor support in TinyGo (just enough to get `fmt.Println` to work).

**Comment by diamondburned** [comment] 2019-07-03 04:14
Does `encoding/binary` work?

On an unrelated note, how well does `fmt.Println` work?

**Comment by deadprogram** [comment] 2019-07-03 07:11
I make pretty extensive use of `encoding/binary` in the USB CDC implementation for the SAMD21 processors, for example: 
https://github.com/tinygo-org/tinygo/blob/master/src/machine/machine_atsamd21.go

`fmt.Println()` works pretty well, but you will surely find edge cases that need further work. Any use of reflection increases the binary size of the executable so I use `println()` unless I need the formatting, or am already using reflection.

**Comment by diamondburned** [comment] 2019-07-04 03:31
So only `encoding/json` doesn't work? What about https://github.com/francoispqt/gojay, it uses no reflections for decoding, and encoding could be done without any as well.

**Comment by aykevl** [comment] 2019-07-05 13:15
The simplest way to know that is to try it out.

**Comment by aykevl** [comment] 2019-07-05 13:16
(closing this because this is not a bug but a question - feel free to continue the discussion)

**Closed by aykevl** 2019-07-05 13:16 UTC
Labels: enhancement
