### ISSUE TITLE
Cryptic compiler error on using non-int parameters in make

### ISSUE THREAD

**Issue by kyegupov** [tinygo-org/tinygo#120] opened 2019-01-04 04:40 UTC
The following code compiles by mainline Go:

    buf := make([]byte, x.methodReturningUint64())

but, when attempting to use that code in TinyGo, it crashes with the following error:

```
Call parameter type does not match function signature!
  %10 = call i64 @"(TypeOfX).methodReturningUint64"(i32 %8, i8* %9, i8* undef), !dbg !24845
 i32  call void @runtime.sliceBoundsCheckMake(i64 %10, i64 %10, i8* undef), !dbg !24846
```

**Comment by aykevl** [comment] 2019-01-04 14:54
On which target is this an issue? I'm asking because this case should be tested in testdata/slice.go, and I can't reproduce on AVR either.

**Comment by kyegupov** [comment] 2019-01-08 03:18
Sorry, the target is WebAssembly.

**Comment by aykevl** [comment] 2019-01-09 15:56
I managed to reproduce this, with the following code:

```go

var x []byte

func main() {
	buf := make([]byte, foo())
	x = buf
}

func foo() uint64 {
	return 3
}
```

Apparently there is a difference between `uint64(3)` and `foo()`. This is why the tests pass but the code here still fails. I'll have to investigate why this is.

**Comment by aykevl** [comment] 2019-01-09 15:59
And this is a bug on all non-64-bit targets I just tested (avr, wasm, cortex-m). So it's not limited to WebAssembly.

**Comment by deadprogram** [comment] 2019-04-11 15:38
I think this issue is now fixed in the `dev` branch, is that correct @aykevl ?

**Comment by aykevl** [comment] 2019-04-11 17:07
Yes, it should be fixed.

**Closed by aykevl** 2019-04-11 17:07 UTC
Labels: bug
