### ISSUE TITLE
On windows, with go 1.18, compiling test compress/flate fails in interp allocating 802KB?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2762] opened 2022-04-10 16:14 UTC
CI fails on windows (and not when cross-compiling!) with go 1.18.
Here's a reconstructed log from https://github.com/tinygo-org/tinygo/pull/2761's https://github.com/tinygo-org/tinygo/runs/5958440739 :

```
$ tinygo test compress/flate
...
ok  	compress/bzip2	0.400s
runtime: VirtualAlloc of 802816 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0x48ee007?, 0xc0d47b2000?})
	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/panic.go:992 +0x76
runtime.sysUsed(0xc0d4748000, 0xc4000)
	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/mem_windows.go:83 +0x1c9
runtime.(*mheap).allocSpan(0x66183c0, 0x62, 0x0, 0x1)
	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/mheap.go:1279 +0x428
runtime.(*mheap).alloc.func1()
	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/mheap.go:912 +0x65
runtime.systemstack()
	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/asm_amd64.s:469 +0x4e

goroutine 3269 [running]:
runtime.systemstack_switch()
	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/asm_amd64.s:436 fp=0xc008275c88 sp=0xc008275c80 pc=0x462fc0
runtime.(*mheap).alloc(0xc4000?, 0x62?, 0x0?)
	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/mheap.go:906 +0x65 fp=0xc008275cd0 sp=0xc008275c88 pc=0x427e45
runtime.(*mcache).allocLarge(0x0?, 0xc3500, 0x1)
	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/mcache.go:213 +0x85 fp=0xc008275d20 sp=0xc008275cd0 pc=0x4180e5
runtime.mallocgc(0xc3500, 0x487db20, 0x1)
	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/malloc.go:1096 +0x5a5 fp=0xc008275d98 sp=0xc008275d20 pc=0x40e545
runtime.makeslice(0x186a0?, 0x0?, 0x0?)
	C:/hostedtoolcache/windows/go/1.18.0/x64/src/runtime/slice.go:103 +0x52 fp=0xc008275dc0 sp=0xc008275d98 pc=0x44c212
github.com/tinygo-org/tinygo/interp.rawValue.clone(...)
	D:/a/tinygo/tinygo/interp/memory.go:679
github.com/tinygo-org/tinygo/interp.(*rawValue).clone(0x0?)
	<autogenerated>:1 +0x4e fp=0xc008275e18 sp=0xc008275dc0 pc=0x7126ee
github.com/tinygo-org/tinygo/interp.object.clone(...)
	D:/a/tinygo/tinygo/interp/memory.go:52
github.com/tinygo-org/tinygo/interp.(*memoryView).store(0xc009a5e7b0, {0x497d038, 0xc005048ef0}, {0xc00810e000?})
	D:/a/tinygo/tinygo/interp/memory.go:316 +0x1f5 fp=0xc008275f78 sp=0xc008275e18 pc=0x70d055
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc00[51](https://github.com/tinygo-org/tinygo/runs/5958440739?check_suite_focus=true#step:18:51)[53](https://github.com/tinygo-org/tinygo/runs/5958440739?check_suite_focus=true#step:18:53)900, 0xc002d2f9a0, {0xc007631510, 0x1, 0x0?}, 0xc009958a80, {0xc008107a50, 0x8})
	D:/a/tinygo/tinygo/interp/interpreter.go:[57](https://github.com/tinygo-org/tinygo/runs/5958440739?check_suite_focus=true#step:18:57)6 +0x2a16 fp=0xc008276ba0 sp=0xc008275f78 pc=0x[70](https://github.com/tinygo-org/tinygo/runs/5958440739?check_suite_focus=true#step:18:70)2cf6
github.com/tinygo-org/tinygo/interp.(*runner).run(0xc005153900, 0xc002d2f[72](https://github.com/tinygo-org/tinygo/runs/5958440739?check_suite_focus=true#step:18:72)0, {0x0, 0x0, 0x24?}, 0x0, {0x48e8a5e, 0x4})
```

**Comment by deadprogram** [comment] 2022-04-11 14:12
So this is basically the main blocker for a new TinyGo release with support for Go 1.18, correct?

**Comment by aykevl** [comment] 2022-04-11 14:39
Yes, although we might also want LLVM 14 (which likely takes some work).

**Comment by Spidy104** [comment] 2022-04-15 05:27
Sorry an offbeat question, is tinygo good for developing various kinds of embedded or iot stuff, or still does it lack something, no offense to the community or the creators, it is a wonderful project...

**Comment by dkegel-fastly** [comment] 2022-04-15 14:46
It's rather good.  The only annoying bits are 1) serialization of structs is a little harder, because 2) reflection isn't fully supported.  So if you need a platform that regular Go doesn't support, tinygo is more than good enough usually.

**Comment by aykevl** [comment] 2022-04-21 14:25
I'm going to rebuild LLVM on Windows to investigate this issue.

**Comment by Spidy104** [comment] 2022-04-21 14:30
> It's rather good. The only annoying bits are 1) serialization of structs is a little harder, because 2) reflection isn't fully supported. So if you need a platform that regular Go doesn't support, tinygo is more than good enough usually.

Is it good for developing professional IoT devices?

**Comment by deadprogram** [comment] 2022-04-21 14:50
> Is it good for developing professional IoT devices?

There are a number of us who think so! :smile_cat:

**Comment by Spidy104** [comment] 2022-04-21 14:53
> > Is it good for developing professional IoT devices?
> 
> There are a number of us who think so! 😸

Thanks, didn't wanna offend the community in any way, it would be really helpful if there was some discord or smth, so that the people could discuss and the community would grow much faster...

**Comment by deadprogram** [comment] 2022-04-21 15:06
Please feel to join our Slack community here: https://app.slack.com/client/T029RQSE6/CDJD3SUP6

**Comment by aykevl** [comment] 2022-04-21 15:37
Take a look here for how to get into the Slack workspace: https://github.com/tinygo-org/tinygo/#getting-help

**Comment by aykevl** [comment] 2022-04-22 00:47
I've almost reproduced this issue:

```
Ayke@sputnik-win10 MINGW64 ~/go/src/github.com/tinygo-org/tinygo (llvm14)
$ build/tinygo test compress/flate
Assertion failed: PrettyStackTraceHead == this && "Pretty stack trace entry destruction is out of order", file C:/Users/Ayke/go/src/github.com/tinygo-org/tinygo/llvm-project/llvm/lib/Support/PrettyStackTrace.cpp, line 229
```

...only I forgot that there's this one bug.

**Comment by aykevl** [comment] 2022-04-22 01:44
Seems to be working here:

```
$ build/tinygo test compress/flate
ld.lld: warning: duplicate /export option: hypot
ld.lld: warning: duplicate /export option: nextafter
ok      compress/flate  13.068s

$ build/tinygo version
tinygo version 0.23.0-dev-24f2bb6c windows/amd64 (using go version go1.18.1 and LLVM version 14.0.0)
```

This is with LLVM 14 because I didn't want to do another LLVM build. It might be that it doesn't run out of memory with LLVM 14. Or it might be that it just works on my laptop and not in other places. (Although I looked at the memory consumption and `tinygo.exe` didn't seem to use an exceptionally large amount of RAM).

**Comment by deadprogram** [comment] 2022-04-22 13:37
@dkegel-fastly is there a straightforward way to test this branch against the Windows CI build that is failing?

https://github.com/tinygo-org/tinygo/pull/2792

**Comment by dkegel-fastly** [comment] 2022-04-22 15:23
yes, left a note on that PR.

**Comment by dankegel** [comment] 2022-04-23 17:31
The test fails reliably, though differently, on a fresh windows installation with clang 14 in wasi like so:
```
$ build/tinygo clean
$ build/tinygo test -target wasi compress/flate
panic: runtime error: slice out of range
           1: 0x8d12 - runtime.slicePanic
                           at C:\Users\dank\src\tinygo\src\runtime\panic.go:42:14
           2: 0x9141e - compress/flate.TestWriterPersistentError
                           at C:\Program Files\Go\src\compress\flate\deflate_test.go:692:7
```

The offending line is 
```
        d = d[:10000] // Keep this test short
```

so it probably can't find its data...?  Yup, len(d) is zero in wasi, and 567198 in native, on windows.  I will file a different bug for that.

**Comment by aykevl** [comment] 2022-04-23 17:53
Huh, I didn't have this issue.

Sadly my Windows install has suddenly given up on me after an update so I won't be able to test this soon.

**Comment by dkegel-fastly** [comment] 2022-04-25 16:54
Removing milestone since this seems to not be reproducible and/or needs more investigation.

**Comment by aykevl** [comment] 2022-09-02 13:41
This appears to be fixed now. Not sure what changed, maybe the move to LLVM 14?
I'm going to close this, unless someone can still reproduce this in the latest release.

Here I've added compress/flate to the Windows tests: https://github.com/tinygo-org/tinygo/pull/3125

**Closed as completed by aykevl** 2022-09-02 13:41 UTC
Labels: bug, windows
