### ISSUE TITLE
Bad append() during initialization when using fmt and testing?

### ISSUE THREAD

**Issue by dkegel-fastly** [tinygo-org/tinygo#2887] opened 2022-06-01 16:54 UTC
This fails "tinygo test" with current dev on mac:

strlist.go:
```
package strlist

import "fmt"

var theStrs []string = buildStrings()

func buildStrings() (vals []string) {
	blue := fmt.Sprintf("%s", "blue")

	// change true to false to work around the problem
	if true {
		vals = append([]string{}, "orange", blue)
	} else {
		vals = make([]string, 2)
		vals[0] = "orange"
		vals[1] = blue
	}
	return vals
}
```

strlist_test.go:
```
package strlist

import "testing"

func TestStrs(t *testing.T) {
	if theStrs[1] == "" {
		t.Fatal("theStrs[1] is empty")
	}
}
```

I was unable to reduce it further.

**Comment by dkegel-fastly** [comment] 2022-06-02 03:08
Also fails:
-  tinygo 0.23 on mac from homebrew
- tinygo dev on linux
- tinygo dev on linux with -target wasi

so it does not seem like a recent regression, nor especially platform-specific

**Comment by dgryski** [comment] 2022-06-07 17:46
I'll take a look at this.

**Comment by dgryski** [comment] 2022-06-09 22:05
Updating here from slack with my notes:
```
before elems[0]= orange elems[1]= blue
sliceAppend: nil nil 0x0000000000000002 0x0000000000000010
allocating... new cap: 0x0000000000000002
before: srcBuf nil elemsBuf 0x000000010bc46d20
srcBuf: 0x000000010bc563a0
memmove( 0x000000010bc563a0 0x000000010bc46d20 0x0000000000000020 )
after src[0]= orange src[1]=
<-- smoking gun that seems to point the finger at the memmove call 
```

Just so explain what this debug log is saying: elemsBuf=0x000000010bc46d20, I cast it to [2]string and print out the elements: elems[0]= orange elems[1]= blue.  Then we print out the address of the srcBuf=0x000000010bc563a0 and the arguments to the memmmove call (note size = 0x20), then cast srcBuf to a [2]string and print those out: after src[0]= orange src[1]= .   I added code to print out elemsBuf as a [2]string after the memmove, and it correctly has elems[1]=blue

**Comment by dgryski** [comment] 2022-06-17 20:06
I'm now beginning to suspect this is a problem wth `interp`.

Edit: confirmed.  Disabling interp fixes the issue.  I noticed it because looking at the disassembly there wasn't a call to `runtime.sliceAppend` after the `fmt.Sprintf()`, only `runtime.print*` calls.

**Comment by radkomih** [comment] 2023-07-07 13:24
@dgryski could you elaborate on how to disable the `interp`? I am experiencing a similar bug in my custom target based on the latest release 0.28.1.

**Comment by dkegel-fastly** [comment] 2023-07-07 14:48
you could try -timeout 0, or hack this line in builder/build.go to always take the error path:
```
                                err := interp.RunFunc(pkgInit, config.Options.InterpTimeout, config.DumpSSA())
                                if err != nil {
                                        return err
                                }
```

**Comment by dgryski** [comment] 2024-10-07 16:47
This appears to be fixed now.  I'm tempted to bisect and see what the commit was that caused the problem to vanish.

**Comment by dgryski** [comment] 2024-10-07 17:09
`git bisect` shows https://github.com/tinygo-org/tinygo/commit/417a26d20c23ea0aaa8f95325bb30172b3e3e9e9 .  Tagging this as "next release".

**Comment by dgryski** [comment] 2024-10-07 17:11
Actually this is in v0.33 already.  Closing.

**Closed as completed by dgryski** 2024-10-07 17:11 UTC
Labels: bug
