### ISSUE TITLE
time.After(): undefined symbol: time.startTimer

### ISSUE THREAD

**Issue by fiurthorn** [tinygo-org/tinygo#2467] opened 2022-01-01 17:39 UTC
Use of time.After() leads to an undefined symbol:

```go
func timer(start, stop chan struct{}) {
	var span time.Time
	select {
	case <-start:
		span = time.Now()
	case <-stop:
		span = time.Time{}
	case <-time.After(250 * time.Microsecond):
		if span.Second() > 5 {
			led.High()
		}
	}
}
```

```bash
fiurthorn@midgard:~/workspace/tiny$ tinygo flash -target=pico ./main.go
tinygo:ld.lld: error: undefined symbol: time.startTimer
>>> referenced by sleep.go:96 (/opt/go/src/time/sleep.go:96)
>>>               /tmp/tinygo3840351086/main.o:(main.timer$gowrapper)
failed to run tool: ld.lld
error: failed to link /tmp/tinygo3840351086/main: exit status 1
```

**Comment by niaow** [comment] 2022-01-02 15:46
This is a duplicate of #1037

**Comment by aykevl** [comment] 2022-01-19 12:47
Yes, going to close this in favor of #1037. Please follow that issue instead.

**Closed as completed by aykevl** 2022-01-19 12:47 UTC
Labels: duplicate
