### ISSUE TITLE
Crash in interp

### ISSUE THREAD

**Issue by aykevl** [tinygo-org/tinygo#648] opened 2019-10-22 13:53 UTC
When running tinygo 0.9, a crash happens at this line:

https://github.com/tinygo-org/tinygo/blob/8a771e3f89679e32aa1f7eeaf630fe1263b91803/interp/values.go#L349

For this program:

https://github.com/hybridgroup/hacklab-2019/blob/master/sensor/arduino/step7/main.go

`tinygo flash -target arduino-nano33 main.go`

**Comment by deadprogram** [comment] 2019-10-24 07:43
I am unable to reproduce this:

```shell
$ tinygo flash -target arduino-nano33 ./sensor/arduino/step7/main.go 
error: failed to reset port /tmp/tinygo386440535/main.bin: opening port: no such file or directory
$ tinygo version
tinygo version 0.9.0 linux/amd64 (using go version go1.13)
```

**Comment by deadprogram** [comment] 2019-11-26 18:40
Unable to reproduce this with the latest `dev` branch. Closing, please reopen if needed.

**Closed by deadprogram** 2019-11-26 18:40 UTC
Labels: bug

**Comment by aykevl** [comment] 2019-11-26 19:04
Now I see this issue again, I realize that it is a duplicate of #742.
