### ISSUE TITLE
DHT11 can't compile in arduino

### ISSUE THREAD

**Issue by MushiTheMoshi** [tinygo-org/tinygo#4111] opened 2024-02-03 15:10 UTC
Hi there,

First of all , thank you for all the amazing work done here, appreciated.

I have an arduino uno which have connected a dht11 humidity sensor, when compiling get the below error.

Hope you can help  to point me in the right direction.

```bash
CMD:
**❯ tinygo flash --target=arduino drivers/examples/dht/main.go --error-limit=0**

ERR:
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 82 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 152 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 168 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 208 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 220 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 552 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 730 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 892 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 1214 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 1294 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 1304 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 1332 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 2322 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 2368 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 2380 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 2400 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 2534 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 2546 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 2612 bytes
tinygo:ld.lld: error: section '.text' will not fit in region 'FLASH_TEXT': overflowed by 2762 bytes
tinygo:ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
failed to run tool: ld.lld
error: failed to link /tmp/tinygo2416875419/main: exit status 1
```

```.bash
tinygo version 0.30.0 linux/amd64 (using go version go1.20.4 and LLVM version 16.0.1)
go version go1.20.4 linux/amd64 <<<tried with other versions
```

**Comment by aykevl** [comment] 2024-02-25 14:35
The example imports `fmt`, which is too big to be usable on an AVR. I suggest using a simpler program that just calls `println` instead.

Closing, because this is not a bug.

**Closed as not planned by aykevl** 2024-02-25 14:35 UTC

**Comment by MushiTheMoshi** [comment] 2024-02-25 15:11
Thank you so much for your help! quick question, how can I troubleshoot this? any tool/command I may use in the future you can kindly suggest me ?

**Comment by aykevl** [comment] 2024-02-25 17:53
In this case it says the flash area is overflowed, which indicates that the binary is too big. Which essentially means you need to reduce the size. There's no specific tool for anything like this I'm afraid.
