### ISSUE TITLE
regression: http-get example in tinygo-drivers fails to compile with dev branch

### ISSUE THREAD

**Issue by ysoldak** [tinygo-org/tinygo#2354] opened 2021-12-07 23:10 UTC
wifinina http-get example in tinygo-drivers repository fails to compile with tinygo from dev branch head.
It compiles fine with latest tinygo release (0.21.0)

Offending change identified to be ec9fd3fb38c5aa97345cae517d6a15204581b851

```
tinygo build -target=arduino-nano33 -size=full -o test.bin ./examples/wifinina/http-get
# path/filepath
/usr/local/Cellar/go/1.17.2/libexec/src/path/filepath/path.go:382:16: Lstat not declared by package os
/usr/local/Cellar/go/1.17.2/libexec/src/path/filepath/match.go:249:18: Lstat not declared by package os
/usr/local/Cellar/go/1.17.2/libexec/src/path/filepath/match.go:324:16: Stat not declared by package os
/usr/local/Cellar/go/1.17.2/libexec/src/path/filepath/path.go:465:18: Lstat not declared by package os
/usr/local/Cellar/go/1.17.2/libexec/src/path/filepath/path.go:501:18: Lstat not declared by package os
/usr/local/Cellar/go/1.17.2/libexec/src/path/filepath/symlink.go:84:17: Lstat not declared by package os
```

**Comment by ysoldak** [comment] 2021-12-07 23:52
PR that fails CircleCi due to this:
https://github.com/tinygo-org/drivers/pull/346

**Comment by dgryski** [comment] 2021-12-08 02:58
Figuring the correct build tags for the `os` package for each platform is a nightmare :(

Why was this not caught when that (or another) PR was merged?

**Comment by dankegel** [comment] 2021-12-08 05:01
Looking...

**Comment by dankegel** [comment] 2021-12-08 05:28
By expanding imports, I found a series of simpler reproducers of the form
```
package main

import foo

func main() {
}
```

where foo is one of:
"tinygo.org/x/drivers/net/http"
"crypto/tls"
"path/filepath"

but I'm not sure how helpful that is.

**Comment by ysoldak** [comment] 2021-12-08 09:07
I mean, no wonder filesystem stuff is not available on "baremetal", shall drivers code be fixed instead that been working by coincidence before? Or shall we have no-op Stat and Lstat stubs for baremetal?

**Comment by dgryski** [comment] 2021-12-08 09:31
I think `ErrNotImplemented` stubs for everything on baremetal is the way to go, until we create some sort of rudimentary in-memory file system or something...

**Comment by deadprogram** [comment] 2021-12-08 09:43
Deciding on filesystem for bare metal also depends on the existence of some device to provide this. See https://github.com/tinygo-org/tinyfs

**Comment by aykevl** [comment] 2021-12-08 15:05
I suspect ec9fd3fb38c5aa97345cae517d6a15204581b851 is to blame. Before that commit, `"path/filepath"` could import the os package as usual. After that commit, `os.Stat` was only available for `!baremetal,!js`.

Not sure how to best catch this. In this specific case, it would have helped to add `"path/filepath"` to testdata/stdlib.go - but that's not really a scalable solution.
One other option is to split the definition and the implementation, for example one generic file (without build tags) defines the exported function:

```go
// some useful comment here
func Stat(name string) (FileInfo, error) {
    return stat(name)
}
```

And then it is implemented another file like this:

```go
// +build <some build tags>

func stat(...) ... { ...}
```

In fact, ec9fd3fb38c5aa97345cae517d6a15204581b851 _almost_ uses this pattern but not quite because of the `!baremetal,!js` build tags.

I've used this pattern here: https://github.com/tinygo-org/tinygo/pull/2332

**Comment by dkegel-fastly** [comment] 2021-12-08 16:41
I'll give it a whirl tonight if nobody beats me to it.

**Comment by aykevl** [comment] 2021-12-08 18:14
> I think `ErrNotImplemented` stubs for everything on baremetal is the way to go, until we create some sort of rudimentary in-memory file system or something...

Essentially, we use a kind of filesystem abstraction for the os package so that packages can set their own implementation (see src/os/filesystem.go). This is useful for embedded devices that don't have an OS and instead use a library (package) to implement the filesystem. It's very similar to the new `io/fs.FS` interface.

I'm fine with returning an `ErrNotImplemented` error for stat functions on baremetal - as long as the functions exist to avoid compile errors.

**Comment by deadprogram** [comment] 2021-12-10 09:35
This issue has been addressed in `dev`. Now closing, please reopen if needed. Thank you everyone!

**Closed as completed by deadprogram** 2021-12-10 09:35 UTC
Labels: bug
