### ISSUE TITLE
wasm panic reason: InstructionTrap(MemoryOutOfBounds) on wasmtime

### ISSUE THREAD

**Issue by hunjixin** [tinygo-org/tinygo#2769] opened 2022-04-12 08:46 UTC
code 
```go
package main

func main() {

}

//go:export test_memory
func test_memory() {
	_ = make([]byte, 1024*65, 1024*65)
}
```

build command: ```tinygo build -o hello.wasm -target wasi --no-debug --panic trap --scheduler none  ./hello.go```

wasm running code:
```rust
use std::{error::Error};
use wasmtime::*;


fn main() -> Result<(), Box<dyn Error>> {
  //  let engine = Engine::new(Config::new().debug_info(true))?;
  let engine = Engine::new(Config::new().debug_info(true))?;
    let module = Module::from_file(&engine, "./go-test/hello.wasm")?;
   // let module2 = Module::from_file(&engine, "/Users/lijunlong/code/wasm_integrate/hello-world/hello_world.wasm")?;
    let mut linker = Linker::new(&engine);
 
   // linker.func_wrap("wasi_snapshot_preview1", "fd_write", |_: i32,_: i32,_: i32,_: i32| 0 as i32)?;
    let data:Vec<u8> = vec![];
    let mut store = Store::new(&engine, data);

    let module = linker.instantiate(&mut store, &module)?;
    linker.instance(&mut store, "go", module)?;


    {
        let start = module.get_typed_func::<(), (), _>(&mut store, "test_memory")?;
        let return_val = start.call(&mut store, ()).unwrap();
        println!("return {:?}", return_val);
    }
}
```
error message:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Trap { reason: InstructionTrap(MemoryOutOfBounds), wasm_trace: [FrameInfo { module_name: None, func_index: 18, func_name: Some("memset"), func_start: FilePos(3278), instr: Some(FilePos(3309)), symbols: [] }, FrameInfo { module_name: None, func_index: 1, func_name: Some("runtime.alloc"), func_start: FilePos(164), instr: Some(FilePos(738)), symbols: [] }, FrameInfo { module_name: None, func_index: 16, func_name: Some("test_memory"), func_start: FilePos(1899), instr: Some(FilePos(1947)), symbols: [] }], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
 }', src/main.rs:24:53
```

**Comment by hunjixin** [comment] 2022-04-12 09:00
https://github.com/tinygo-org/tinygo/blob/3883550c446fc8b14115366284316290f3d3c4b1/src/runtime/gc_conservative.go#L338

memzero panic

**Comment by dgryski** [comment] 2022-04-12 17:46
A sightly better stack trace:
```
~/go/src/github.com/dgryski/bug $ tinygo build -target=wasi -opt=1  -o test.wasm bug.go && WASMTIME_BACKTRACE_DETAILS=1 wasmtime run ./test.wasm --invoke test_memory

panic: runtime error: gc: block pointing inside metadata
Error: failed to run main module `./test.wasm`

Caused by:
    0: failed to invoke `test_memory`
    1: wasm trap: wasm `unreachable` instruction executed
       wasm backtrace:
           0: 0x2010 - runtime.abort
                           at /Users/dgryski/go/src/github.com/tinygo-org/tinygo/src/runtime/runtime_tinygowasm.go:62:6
           1:  0x6a5 - runtime.runtimePanic
                           at /Users/dgryski/go/src/github.com/tinygo-org/tinygo/src/runtime/panic.go:20:7
           2: 0x208f - (runtime.gcBlock).address
                           at /Users/dgryski/go/src/github.com/tinygo-org/tinygo/src/runtime/gc_conservative.go:115:15
           3: 0x1262 - (runtime.gcBlock).pointer
                           at /Users/dgryski/go/src/github.com/tinygo-org/tinygo/src/runtime/gc_conservative.go:108:33
           4:  0xadc - runtime.alloc
                           at /Users/dgryski/go/src/github.com/tinygo-org/tinygo/src/runtime/gc_conservative.go:331:47
           5: 0x42b5 - test_memory
                           at /Users/dgryski/go/src/github.com/dgryski/bug/bug.go:11:10
```

**Comment by dgryski** [comment] 2022-04-12 18:38
The problem appears to be that when invoking functions externally, the runtime environment (heap, etc) are not initialized so the allocation fails.

**Comment by hunjixin** [comment] 2022-04-13 00:51
> The problem appears to be that when invoking functions externally, the runtime environment (heap, etc) are not initialized so the allocation fails.

and if i just small slice, it will be no error. heap should be okay, because if i set gc to leaking,  this code can pass

**Comment by dgryski** [comment] 2022-04-13 00:58
If it's a small slice it will be allocated on the stack instead.

**Comment by hunjixin** [comment] 2022-04-13 01:27
the grow instruction has been executed before , and it is said that the memory space has been allocated.  or allocate not success?

**Comment by hunjixin** [comment] 2022-04-13 12:14
@dgryski  have try you cmd, but got different error, i am use latest dev branch
```
lijunlong@lijunlongdembp go-test % tinygo build -target=wasi -opt=1  -o test.wasm ./hello.go && WASMTIME_BACKTRACE_DETAILS=1 wasmtime run ./test.wasm --invoke test_memory
Error: failed to run main module `./test.wasm`

Caused by:
    0: failed to invoke `test_memory`
    1: wasm trap: out of bounds memory access
       wasm backtrace:
           0: 0x2ab1 - memset
                           at /Users/lijunlong/code/tinygo/lib/wasi-libc/libc-top-half/musl/src/string/memset.c:15:9
           1:  0xacc - runtime.alloc
       
           2: 0x248f - test_memory
                           at /Users/lijunlong/code/wasm_integrate/go-test/hello.go:9:10
```

**Comment by hunjixin** [comment] 2022-04-13 12:53
i knew the rease, set gcDebug to true

**Comment by hunjixin** [comment] 2022-04-13 13:25
add more log to gc loop and got result like this

```go
func alloc(size uintptr, layout unsafe.Pointer) unsafe.Pointer {
	if size == 0 {
		return unsafe.Pointer(&zeroSizedAlloc)
	}

	neededBlocks := (size + (bytesPerBlock - 1)) / bytesPerBlock

	// Continue looping until a run of free blocks has been found that fits the
	// requested size.
	index := nextAlloc
	numFreeBlocks := uintptr(0)
	heapScanCount := uint8(0)

	for {
		println("index", index, "nextAlloc", nextAlloc, "endBlock", endBlock)
		if index == nextAlloc {
			if heapScanCount == 0 {
```
log
```
index nil nextAlloc nil endBlock nil
index 0x00000001 nextAlloc nil endBlock nil
index 0x00000002 nextAlloc nil endBlock nil
index 0x00000003 nextAlloc nil endBlock nil
index 0x00000004 nextAlloc nil endBlock nil
index 0x00000005 nextAlloc nil endBlock nil
index 0x00000006 nextAlloc nil endBlock nil
index 0x00000007 nextAlloc nil endBlock nil
index 0x00000008 nextAlloc nil endBlock nil
index 0x00000009 nextAlloc nil endBlock nil
index 0x0000000a nextAlloc nil endBlock nil
index 0x0000000b nextAlloc nil endBlock nil
index 0x0000000c nextAlloc nil endBlock nil
index 0x0000000d nextAlloc nil endBlock nil
index 0x0000000e nextAlloc nil endBlock nil
index 0x0000000f nextAlloc nil endBlock nil
index 0x00000010 nextAlloc nil endBlock nil
index 0x00000011 nextAlloc nil endBlock nil
index 0x00000012 nextAlloc nil endBlock nil
index 0x00000013 nextAlloc nil endBlock nil
index 0x00000014 nextAlloc nil endBlock nil
index 0x00000015 nextAlloc nil endBlock nil
index 0x00000016 nextAlloc nil endBlock nil
index 0x00000017 nextAlloc nil endBlock nil
index 0x00000018 nextAlloc nil endBlock nil
index 0x00000019 nextAlloc nil endBlock nil
index 0x0000001a nextAlloc nil endBlock nil
index 0x0000001b nextAlloc nil endBlock nil
index 0x0000001c nextAlloc nil endBlock nil
index 0x0000001d nextAlloc nil endBlock nil
index 0x0000001e nextAlloc nil endBlock nil
index 0x0000001f nextAlloc nil endBlock nil
index 0x00000020 nextAlloc nil endBlock nil
index 0x00000021 nextAlloc nil endBlock nil
index 0x00000022 nextAlloc nil endBlock nil
index 0x00000023 nextAlloc nil endBlock nil
index 0x00000024 nextAlloc nil endBlock nil
index 0x00000025 nextAlloc nil endBlock nil
index 0x00000026 nextAlloc nil endBlock nil
index 0x00000027 nextAlloc nil endBlock nil
index 0x00000028 nextAlloc nil endBlock nil
index 0x00000029 nextAlloc nil endBlock nil
index 0x0000002a nextAlloc nil endBlock nil
index 0x0000002b nextAlloc nil endBlock nil
index 0x0000002c nextAlloc nil endBlock nil
index 0x0000002d nextAlloc nil endBlock nil
index 0x0000002e nextAlloc nil endBlock nil
index 0x0000002f nextAlloc nil endBlock nil
index 0x00000030 nextAlloc nil endBlock nil
index 0x00000031 nextAlloc nil endBlock nil
index 0x00000032 nextAlloc nil endBlock nil
index 0x00000033 nextAlloc nil endBlock nil
index 0x00000034 nextAlloc nil endBlock nil
index 0x00000035 nextAlloc nil endBlock nil
index 0x00000036 nextAlloc nil endBlock nil
index 0x00000037 nextAlloc nil endBlock nil
index 0x00000038 nextAlloc nil endBlock nil
index 0x00000039 nextAlloc nil endBlock nil
index 0x0000003a nextAlloc nil endBlock nil
index 0x0000003b nextAlloc nil endBlock nil
index 0x0000003c nextAlloc nil endBlock nil
index 0x0000003d nextAlloc nil endBlock nil
index 0x0000003e nextAlloc nil endBlock nil
```
index is alway increase but not trigger grow memory,  maybe condition check problem?

**Comment by hunjixin** [comment] 2022-04-13 13:54
when i add colde like this, works fine, @dgryski  is this a bug?
```
		if index == endBlock {

			if index == gcBlock(0) {
				continue
			}

			index = 0
			// Reset numFreeBlocks as allocations cannot wrap.
			numFreeBlocks = 0
		}
```

**Comment by dgryski** [comment] 2022-04-13 17:37
Yes and no.  The problem is that calling `test_memory` without any of the other existing runtime initialization doesn't end up calling `calculateHeapAddresses()`, but a regular `continue` if `index == endBlock == gcBlock(0)` is also incorrect.  What ends up happening is we try to grow the heap, and in that process we *do* end up calling `calculateHeapAddresses()`, but I don't think that's the correct fix.

**Comment by hunjixin** [comment] 2022-04-14 01:18
> Yes and no. The problem is that calling `test_memory` without any of the other existing runtime initialization doesn't end up calling `calculateHeapAddresses()`, but a regular `continue` if `index == endBlock == gcBlock(0)` is also incorrect. What ends up happening is we try to grow the heap, and in that process we _do_ end up calling `calculateHeapAddresses()`, but I don't think that's the correct fix.

I agree with you, I think the reason here is that wasm does not support the usage of non-main at present. It may be necessary to execute some preamble code to exec initHeap func

**Comment by inkeliz** [comment] 2022-04-22 00:20
I hit the same issue. I'm calling one external functions [with wazero](https://github.com/tetratelabs/wazero). That only affects `-gc conservative`. If you compile with `-gc leaking` it will call `grow` correctly and doesn't run out of memory. However, compiling with the default GC it will run out of memory and doesn't call `grow` functioms from WASM.

----

EDIT: For anyone in the future, and as @dgryski points in the comments, the wasm-host should call `_start` before calling any other external function. The `_start` function seems to be part of WASI spec.

**Comment by hunjixin** [comment] 2022-05-20 02:14
update.   i have call _start before invoke by manual edit wat file and than compiler to wasm
```wasm
  (func $invoke (type 2) (param i32) (result i32)
    (local i32 i32 i32)
    call $_start
    global.get $__stack_pointer
    i32.const 16
    i32.sub
    local.tee 1
    global.set $__stack_pointer
```
when use default scheduler, its okay to running, but when set scheduler to none. unable to run . and log like this
```
heapStart:         0x00010210

heapEnd:           0x00020000

total size:        0x0000fdf0

metadata size:     0x000003e9

metadataStart:     0x0001fc17

# of blocks:       0x00000fa0

# of block states: 0x00000fa4


index nil nextAlloc nil endBlock 0x00000fa0

index 0x00000001 nextAlloc nil endBlock 0x00000fa0

index 0x00000002 nextAlloc nil endBlock 0x00000fa0

index 0x00000003 nextAlloc nil endBlock 0x00000fa0

index 0x00000004 nextAlloc nil endBlock 0x00000fa0

index 0x00000005 nextAlloc nil endBlock 0x00000fa0

index 0x00000006 nextAlloc nil endBlock 0x00000fa0

index 0x00000007 nextAlloc nil endBlock 0x00000fa0

index 0x00000008 nextAlloc nil endBlock 0x00000fa0

index 0x00000009 nextAlloc nil endBlock 0x00000fa0

index 0x0000000a nextAlloc nil endBlock 0x00000fa0

index 0x0000000b nextAlloc nil endBlock 0x00000fa0

index 0x0000000c nextAlloc nil endBlock 0x00000fa0

index 0x0000000d nextAlloc nil endBlock 0x00000fa0

index 0x0000000e nextAlloc nil endBlock 0x00000fa0

index 0x0000000f nextAlloc nil endBlock 0x00000fa0
```

**Comment by hunjixin** [comment] 2022-05-23 01:18
> update. i have call _start before invoke by manual edit wat file and than compiler to wasm
> 
> ```webassembly
>   (func $invoke (type 2) (param i32) (result i32)
>     (local i32 i32 i32)
>     call $_start
>     global.get $__stack_pointer
>     i32.const 16
>     i32.sub
>     local.tee 1
>     global.set $__stack_pointer
> ```
> 
> when use default scheduler, its okay to running, but when set scheduler to none. unable to run . and log like this
> 
> ```
> heapStart:         0x00010210
> 
> heapEnd:           0x00020000
> 
> total size:        0x0000fdf0
> 
> metadata size:     0x000003e9
> 
> metadataStart:     0x0001fc17
> 
> # of blocks:       0x00000fa0
> 
> # of block states: 0x00000fa4
> 
> 
> index nil nextAlloc nil endBlock 0x00000fa0
> 
> index 0x00000001 nextAlloc nil endBlock 0x00000fa0
> 
> index 0x00000002 nextAlloc nil endBlock 0x00000fa0
> 
> index 0x00000003 nextAlloc nil endBlock 0x00000fa0
> 
> index 0x00000004 nextAlloc nil endBlock 0x00000fa0
> 
> index 0x00000005 nextAlloc nil endBlock 0x00000fa0
> 
> index 0x00000006 nextAlloc nil endBlock 0x00000fa0
> 
> index 0x00000007 nextAlloc nil endBlock 0x00000fa0
> 
> index 0x00000008 nextAlloc nil endBlock 0x00000fa0
> 
> index 0x00000009 nextAlloc nil endBlock 0x00000fa0
> 
> index 0x0000000a nextAlloc nil endBlock 0x00000fa0
> 
> index 0x0000000b nextAlloc nil endBlock 0x00000fa0
> 
> index 0x0000000c nextAlloc nil endBlock 0x00000fa0
> 
> index 0x0000000d nextAlloc nil endBlock 0x00000fa0
> 
> index 0x0000000e nextAlloc nil endBlock 0x00000fa0
> 
> index 0x0000000f nextAlloc nil endBlock 0x00000fa0
> ```

has fixed in latest dev

**Comment by codefromthecrypt** [comment] 2022-09-07 06:54
I would recommend we close this issue

per this comment, https://github.com/tinygo-org/tinygo/issues/2769#issuecomment-1105877815

the most important point is anything wasi expects `_start` to be called first. So, let's assume that's the case for now.

Ack there are other issues about this type of concern (calling exports after _start completed), but I suspect this can close and allow focus on other issues, right @hunjixin?

**Comment by hunjixin** [comment] 2022-09-07 07:06
yes i think so. i would close this issue and link with the non main issue

**Comment by hunjixin** [comment] 2022-09-07 07:08
https://github.com/tinygo-org/tinygo/issues/2703

**Closed as completed** 2022-09-15 01:00 UTC
Labels: enhancement, wasm
