### ISSUE TITLE
panic: compiler: could not store type code number inside interface type code

### ISSUE THREAD

**Issue by ahmedalhulaibi** [tinygo-org/tinygo#2169] opened 2021-10-11 14:59 UTC
Info:
```
$ go version
go version go1.17.2 windows/amd64
$ tinygo version
tinygo version 0.20.0 windows/amd64 (using go version go1.17.2 and LLVM version 11.0.0)
$ avr-gcc -dumpversion
11.1.0
$ avrdude -version
avrdude version 6.3-20171130, URL: <http://savannah.nongnu.org/projects/avrdude/>
```
_____
## Problem
I was trying to compile with the the [`hd44780` driver](https://github.com/tinygo-org/drivers/tree/release/hd44780) and I was getting this compiler error. Here's a gist with the driver source copied into one file https://gist.github.com/ahmedalhulaibi/b033cb8d44eaf64d0ffcae77093999cb

```
$ tinygo build -target arduino -o crystalball.exe
panic: compiler: could not store type code number inside interface type code

goroutine 16 [running]:
github.com/tinygo-org/tinygo/transform.LowerReflect({0x2fdd7800})
        D:/a/1/s/transform/reflect.go:185 +0x905
github.com/tinygo-org/tinygo/transform.Optimize({0xc0010e1dc8}, 0xc000307f20, 0x2, 0x0, 0x5)
        D:/a/1/s/transform/optimizer.go:91 +0x4a5
github.com/tinygo-org/tinygo/builder.optimizeProgram({0x2fb16808}, 0xc000307f20)
        D:/a/1/s/builder/build.go:740 +0x1ed
github.com/tinygo-org/tinygo/builder.Build.func2(0xc000686300)
        D:/a/1/s/builder/build.go:386 +0x657
github.com/tinygo-org/tinygo/builder.jobWorker(0xc0006859a0, 0x2d)
        D:/a/1/s/builder/jobs.go:182 +0xad
created by github.com/tinygo-org/tinygo/builder.runJobs
        D:/a/1/s/builder/jobs.go:101 +0x1a5
```
___

I tried something simpler and recreated the error with a much smaller program

```go
package main

import "fmt"

func main() {
    fmt.Println("hello")
}
```
```
$ tinygo build -target arduino -o blink.exe
panic: compiler: could not store type code number inside interface type code

goroutine 14 [running]:
github.com/tinygo-org/tinygo/transform.LowerReflect({0x2fbb6310})
        D:/a/1/s/transform/reflect.go:185 +0x905
github.com/tinygo-org/tinygo/transform.Optimize({0xc003085dc8}, 0xc0002f5260, 0x2, 0x0, 0x5)
        D:/a/1/s/transform/optimizer.go:91 +0x4a5
github.com/tinygo-org/tinygo/builder.optimizeProgram({0x40437a0}, 0xc0002f5260)
        D:/a/1/s/builder/build.go:740 +0x1ed
github.com/tinygo-org/tinygo/builder.Build.func2(0x0)
        D:/a/1/s/builder/build.go:386 +0x657
github.com/tinygo-org/tinygo/builder.jobWorker(0x0, 0x0)
        D:/a/1/s/builder/jobs.go:182 +0xad
created by github.com/tinygo-org/tinygo/builder.runJobs
        D:/a/1/s/builder/jobs.go:101 +0x1a5
```

## Temporary Workaround
I managed to narrow down the problem to the `Buser` interface. When I replaced `Buser` with the `*GPIO` implementation, I was able to compile without any issues. https://gist.github.com/ahmedalhulaibi/b033cb8d44eaf64d0ffcae77093999cb#file-crystalball-go-L282-L284

**Comment by soypat** [comment] 2021-10-12 20:21
Hey! I managed to replicate your issue on `linux/amd64`.

Quick question, why are you using the `fmt` package to print data? I'd suggest using `println`, from my experience that's the standard way (on TinyGo only, of course!) of writing data to USB or UART. It would be the equivalent of Arduino's `Serial.Println`.

**Comment by ahmedalhulaibi** [comment] 2021-10-12 21:29
The example with fmt was just an example to recreate the problem. I don't actually need print. Although that is good to know, thanks for the tip!

My issue is when I import the hd44780 tiny go driver I get a compiler error. The compiler error originates from the driver source. To make sure I copied the driver source into a gist and replaced the 'Buser' interface with the relevant implementation '*GPIO' and it compiled

https://gist.github.com/ahmedalhulaibi/b033cb8d44eaf64d0ffcae77093999cb#file-crystalball-go-L282-L289

**Comment by ahmedalhulaibi** [comment] 2021-10-12 21:43
Specifically the issue is here: https://github.com/tinygo-org/drivers/blob/1cbf1a6f3d2c9758bfe0063e8b55be77d1890c49/hd44780/hd44780.go#L27-L48

```go
type Buser interface {
	io.ReadWriter
	SetCommandMode(set bool)
	WriteOnly() bool
}


type Device struct {
	bus          Buser    // This is failing to be compiled, changing this to a concrete type resolves the issue
        // bus          *GPIO    // This compiles without issues
        // other fields....
}
```

**Comment by soypat** [comment] 2021-10-12 21:51
Sorry, jumped the gun there. I think @aykevl or @niaow would probably be able to help you with compiler internals.

**Comment by ahmedalhulaibi** [comment] 2021-10-12 22:28
No problem at all, I appreciate the quick response. I started using the docker containers for building and recreated the issue on the following versions.

- 0.20.0
- 0.19.0
- 0.18.0

Surprisingly, 0.17.0 worked! I'm assuming this commit changed how interfaces are optimized https://github.com/tinygo-org/tinygo/commit/cd517a30afd608dc6dd52745690c6dbd4f7fb010

**Comment by zdima** [comment] 2021-12-03 16:11
I was able to reproduce the same panic with `time.Ticker` on dev branch:
```
package main

import "time"

func main() {
	_ = time.NewTicker(time.Millisecond * 700)
}
```

```
$ tinygo build -o test -target=arduino main.go 
panic: compiler: could not store type code number inside interface type code

goroutine 13 [running]:
github.com/tinygo-org/tinygo/transform.LowerReflect(0x104306d50)
	.../transform/reflect.go:185 +0x9b8
github.com/tinygo-org/tinygo/transform.Optimize(0x104306d50, 0x1400020ad80, 0x2, 0x2, 0x5, 0x0, 0x0, 0x0)
	.../transform/optimizer.go:91 +0x380
github.com/tinygo-org/tinygo/builder.optimizeProgram(0x104306d50, 0x1400020ad80, 0x14000732a50, 0x2)
	.../builder/build.go:844 +0x128
github.com/tinygo-org/tinygo/builder.Build.func2(0x14001858900, 0x0, 0x0)
	.../builder/build.go:463 +0x614
github.com/tinygo-org/tinygo/builder.jobWorker(0x14000e91020, 0x14000e90fc0)
	.../builder/jobs.go:191 +0xb4
created by github.com/tinygo-org/tinygo/builder.runJobs
	.../builder/jobs.go:110 +0x164
```

**Comment by zdima** [comment] 2021-12-03 17:01
@aykevl, is there a way to print what line or field causing this issue?
https://github.com/tinygo-org/tinygo/blob/06df31944c6af706d6cb8b30a2e92d19060436d2/transform/reflect.go#L180-L186

**Comment by dgryski** [comment] 2021-12-03 18:15
If you don't mind patching your compiler, you can add the following:
```
diff --git a/transform/reflect.go b/transform/reflect.go
index c4ecae77..17256c05 100644
--- a/transform/reflect.go
+++ b/transform/reflect.go
@@ -182,7 +182,7 @@ func LowerReflect(mod llvm.Module) {
                        // That's less efficient but better than not working at all.
                        // Particularly important on systems with 16-bit pointers (e.g.
                        // AVR).
-                       panic("compiler: could not store type code number inside interface type code")
+                       panic("compiler: could not store type code number inside interface type code:" + t.name)
                }

                // Replace each use of the type code global with the constant type code.
```

**Comment by zdima** [comment] 2021-12-03 19:04
@dgryski looks like something to do with having multiple slices _**of different types**_ in the structure that is passed as interface.
Reduce test to reproduce this:
```
package main

type X1 struct{ a int64 }
type X2 struct{ a int64 }

type Y struct {
	zone []X1
	tx   []X2
}

func check(c interface{}) {}

func main() {
	var l *Y
	check(l)
}
```

`
$ tinygo build -o test -target=arduino .
panic: compiler: could not store type code number inside interface type code:reflect/types.type:pointer:slice:named:main.X1
`

**The compiler is not panicing when commenting Y.zone or Y.tx**

**Comment by zdima** [comment] 2021-12-03 20:04
the `state` and `num` (0x17CE5) at a time of crash if it helps
![Screen Shot 2021-12-03 at 2 58 31 PM](https://user-images.githubusercontent.com/298260/144665207-0710c681-e8fe-492d-b348-6bd822b88046.png)

**Comment by aykevl** [comment] 2021-12-28 22:24
Yeah, this is a bug only on AVR. It should be fixed some day once I finally finish my reflect rewrite, however it is possible to provide a workaround for it in the meantime. I might write it if there is enough demand for it.

**Comment by stephenfeagin** [comment] 2022-01-20 15:48
@aykevl I'd love to get a workaround if it's possible. I'm also getting this panic when using the hd44780 driver with an Arduino Uno on Ubuntu 20.04. My `main.go` is the hd44780 example almost verbatim, just changing pins for my board.

Error:
```
$ tinygo build -target arduino -o led
panic: compiler: could not store type code number inside interface type code

goroutine 10 [running]:
github.com/tinygo-org/tinygo/transform.LowerReflect({0x7f80c44546a0})
        /home/circleci/project/transform/reflect.go:185 +0x905
github.com/tinygo-org/tinygo/transform.Optimize({0xc000061dc8}, 0xc00028ac30, 0x2, 0x0, 0x5)
        /home/circleci/project/transform/optimizer.go:91 +0x4d7
github.com/tinygo-org/tinygo/builder.optimizeProgram({0x7f80c41489d8}, 0xc00028ac30)
        /home/circleci/project/builder/build.go:844 +0x1f4
github.com/tinygo-org/tinygo/builder.Build.func2(0x0)
        /home/circleci/project/builder/build.go:463 +0x66d
github.com/tinygo-org/tinygo/builder.jobWorker(0x0, 0x0)
        /home/circleci/project/builder/jobs.go:191 +0xad
created by github.com/tinygo-org/tinygo/builder.runJobs
        /home/circleci/project/builder/jobs.go:110 +0x229
```

System Info:
```
$ go version
go version go1.17.6 linux/amd64

$ tinygo version
tinygo version 0.21.0 linux/amd64 (using go version go1.17.6 and LLVM version 11.0.0)

$ avr-gcc -dumpversion
5.4.0

$ arvdude -version
    ...
avrdude version 6.3-20171130, URL: <http://savannah.nongnu.org/projects/avrdude/>

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

$uname -srvpio
Linux 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 GNU/Linux
```

**Comment by ahmedalhulaibi** [comment] 2022-01-21 20:18
@stephenfeagin One workaround is to fork the driver code so you can remove the interface and replace it with the concrete type. It's not ideal but it will get the code running.

**Comment by dgryski** [comment] 2023-03-23 05:50
This should be fixed now.

**Comment by deadprogram** [comment] 2023-06-14 09:04
This is part of the `v0.28` release so now closing this issue. Thanks!

**Closed as completed by deadprogram** 2023-06-14 09:04 UTC
Labels: bug
