### ISSUE TITLE
tinygo error: Linking globals named 'malloc': symbol multiply defined!

### ISSUE THREAD

**Issue by TotTheMax** [tinygo-org/tinygo#2243] opened 2021-11-09 02:59 UTC
tinygo build 

tinygo error: Linking globals named 'malloc': symbol multiply defined!

version:
╰─$ tinygo version                                                                                                                
tinygo version 0.20.0 darwin/amd64 (using go version go1.17 and LLVM version 11.0.0)
wasme --version
wasme version 0.0.32

**Comment by TotTheMax** [comment] 2021-11-09 03:02
![image](https://user-images.githubusercontent.com/38995438/140854265-b9613edc-1f7b-4a2d-b2c5-e2265117198c.png)

**Comment by aykevl** [comment] 2021-11-10 18:27
Can you provide a reproducer? I can't investigate this issue without looking at the source code.

**Comment by deadprogram** [comment] 2024-12-04 10:19
Closing due to age and lack of info.

**Closed as completed by deadprogram** 2024-12-04 10:19 UTC
Labels: wasm
